### PR TITLE
Update C++ version to C++17 for our project files

### PR DESCRIPTION
**Pull request by jrobeson**

### CODE REVIEW

**Comment by jrobeson** [comment]
I'd actually like to use C++20, but your current MSVC version is a tad too old. Let me know whenever you upgrade it.

**Comment by TwnKey** [comment]
I upgraded it to version 14.29.30133, I think it should support C++20 (not sure if it is a full support though); we can make the switch and I'll let you know if I encounter any problem.

**Comment by jrobeson** [comment]
that doesn't sound like the correct version, since that'd be before VS 2015 as per https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-160

**Comment by TwnKey** [comment]
Actually my version of Visual Studio is correct I believe (it is 16.11) and the MSVC compiler version that came with it is 14.29.30133 (or 19.29.30133, that is what I'm getting when running cl.exe)

**Comment by jrobeson** [comment]
16.11 is probably the important number here then. I still think you should merge this PR, for the sake of #8 and i'll make another one later for C++20

**Pull request merged**
